# Generated by Django 5.2.1 on 2026-03-12 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('final_score', models.IntegerField(default=0)),
                ('missions_completed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=20)),
                ('violations', models.PositiveIntegerField(default=0)),
                ('integrity', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(unique=True)),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('level_group', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('ROOKIE', 'Rookie'), ('AGENT', 'Agent'), ('SPECIALIST', 'Specialist'), ('EXPERT', 'Expert'), ('ELITE', 'Elite')], max_length=20)),
                ('brief', models.TextField()),
                ('target_hint', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=200)),
                ('time_limit', models.PositiveIntegerField(default=300)),
                ('hint_text', models.TextField()),
                ('hint_cost', models.PositiveIntegerField(default=150)),
                ('total_clues', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('solved', models.BooleanField(default=False)),
                ('score_earned', models.IntegerField(default=0)),
                ('time_taken', models.PositiveIntegerField(default=0)),
                ('wrong_attempts', models.PositiveIntegerField(default=0)),
                ('hint_used', models.BooleanField(default=False)),
                ('clues_found', models.PositiveIntegerField(default=0)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.mission')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='game.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='MissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('has_clue', models.BooleanField(default=False)),
                ('clue_tag', models.CharField(blank=True, max_length=30)),
                ('clue_text', models.TextField(blank=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='game.mission')),
            ],
            options={
                'ordering': ['path', 'filename'],
            },
        ),
        migrations.CreateModel(
            name='MissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('time_label', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('INFO', 'INFO'), ('WARN', 'WARN'), ('ERR', 'ERR'), ('CRIT', 'CRIT')], max_length=10)),
                ('message', models.CharField(max_length=500)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='game.mission')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operative_name', models.CharField(max_length=50, unique=True)),
                ('total_score', models.IntegerField(default=0)),
                ('best_score', models.IntegerField(default=0)),
                ('missions_completed', models.PositiveIntegerField(default=0)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('missions_completed', models.PositiveIntegerField()),
                ('integrity', models.PositiveIntegerField()),
                ('time_taken', models.PositiveIntegerField(default=0)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamesession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lb_entries', to='game.playerprofile')),
            ],
            options={
                'ordering': ['-score', 'time_taken'],
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='game.playerprofile'),
        ),
        migrations.CreateModel(
            name='ViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=100)),
                ('penalty', models.PositiveIntegerField(default=0)),
                ('severity', models.CharField(default='low', max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_logs', to='game.gamesession')),
            ],
        ),
    ]
